invoker/core/src/test/java/com/google/cloud/functions/invoker/IntegrationTest.java
Otherwise we may get a BindException when the next test method runs,
since the previous process hasn't exited yet and is still listening
to the server port.
=> Wait for process completion after each test method.

README.md
It was accidentally uncorrected in a previous commit.
=> Restore the corrected plugin invocation line.

invoker/core/src/main/java/com/google/cloud/functions/invoker/runner/Invoker.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/IntegrationTest.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/testfunctions/Multipart.java
Jetty requires a servlet to be configured explicitly before it will accept multipart input.
=> Fix multipart support for HTTP functions.

invoker/core/src/main/java/com/google/cloud/functions/invoker/FunctionLoader.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/runner/Invoker.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/BackgroundFunctionTest.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/HttpFunctionTest.java
The code is complicated by the support for legacy "ClassName.method" way of
specifying function targets, which we will delete when we delete java8 support
from GCF. Under the assumption that the user did mean to use the new form, we
remember what the ClassNotFoundException was that caused us to fail, and we
include that in the cause chain of the final exception. That way the user can
see a possible ExceptionInInitializerError or the like that might be the
underlying reason for the failure.
=> Keep ClassNotFoundException as cause when reporting function not found.

functions-framework-api/src/main/java/com/google/cloud/functions/BackgroundFunction.java, functions-framework-api/src/main/java/com/google/cloud/functions/HttpFunction.java, functions-framework-api/src/main/java/com/google/cloud/functions/HttpMessage.java, functions-framework-api/src/main/java/com/google/cloud/functions/HttpRequest.java, functions-framework-api/src/main/java/com/google/cloud/functions/HttpResponse.java, functions-framework-api/src/main/java/com/google/cloud/functions/RawBackgroundFunction.java
* Some code extracts had strange spacing because of longstanding bugs in the javadoc tool.
* Most javadoc warnings have been fixed, often at the cost of annoyingly redundant
`@param` and `@return` tags.
=> Improve the javadoc for the API.

invoker/function-maven-plugin/src/main/java/com/google/cloud/functions/plugin/RunFunction.java
This PR correctly builds the runtime classpath for the function. The current implementation only includes compile dependencies which is broken for all but the most trivial cases.
=> Correctly resolve function runtime classpath in Maven plugin. Fixes #30

functions-framework-api/pom.xml, invoker/core/pom.xml, invoker/core/src/main/java/com/google/cloud/functions/invoker/CloudEventsServletBinaryMessageReader.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/NewBackgroundFunctionExecutor.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/runner/Invoker.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/IntegrationTest.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/NewBackgroundFunctionExecutorTest.java, invoker/pom.xml
Also explicitly require Java version 11, since we no longer support Java 8.
This version of the SDK makes a cleaner separation between API and implementation, and our use of it is accordingly simplified.
=> Switch to V2 of the CloudEvents SDK.

invoker/function-maven-plugin/src/main/java/com/google/cloud/functions/plugin/DeployFunction.java, invoker/function-maven-plugin/src/test/java/com/google/cloud/functions/plugin/DeployFunctionTest.java
As defined in the [docs](https://cloud.google.com/functions/docs/env-var), the command should be  `--env-vars-file`instead of `--env-var-file` (note the `s`missing) 
Running the original code we just get Error: ` unrecognized arguments: --env-var-file=ci-env.yaml (did you mean '--env-vars-file'?)`
issue ref: #39
=> Use the command param env-vars-file instead of env-var-file.

functions-framework-api/pom.xml, invoker/core/pom.xml, invoker/core/src/main/java/com/google/cloud/functions/invoker/BackgroundFunctionExecutor.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/IntegrationTest.java, invoker/pom.xml
Temporarily switch the Functions Framework to use a SNAPSHOT version of the API.
=> Update to Milestone 2 of the CloudEvents SDK.

invoker/core/src/main/java/com/google/cloud/functions/invoker/BackgroundFunctionExecutor.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/CloudEventsServletBinaryMessageReader.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/runner/Invoker.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/IntegrationTest.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/testfunctions/CloudEventSnoop.java
This means functions that receive a CloudEvent payload and dispatch it to a user function that expects a CloudEvent object. We do not yet handle converting a CloudEvent payload to the form expected by legacy GCF functions.
=> Add support for native CloudEvents functions.

README.md
- Adds badges to README
- Maven Central badge for main API
- GitHub Actions badge
Similar to this repo: https://github.com/googleapis/google-cloud-java
Preview:
=> docs: add ci and maven central badges

invoker/core/src/test/java/com/google/cloud/functions/invoker/GcfEventsTest.java, invoker/core/src/test/resources/firestore_complex.json, invoker/core/src/test/resources/pubsub_binary.json
These tests check what is in the `data` field of the CloudEvents that we
translate from legacy events. For now they are not all that useful, because that
field is basically just a copy of the JSON payload of the legacy event. But we
do rearrange things slightly for PubSub events, and we are likely to do so for
Firebase events too in the future. Furthermore, if we eventually have a library
of classes representing the various event payloads, then we can use that library
instead of working with the JSON directly. That is what
google-cloudevents-dotnet does, for example.
=> Add more tests on the data of translated CloudEvents.

functions-framework-api/src/main/java/com/google/cloud/functions/Context.java
Removes 5 warnings when running `mvn install`.
```
5 warnings
[WARNING] Javadoc Warnings
[WARNING] /Users/timmerman/Documents/github/googlecloudplatform/functions-framework-java/functions-framework-api/src/main/java/com/google/cloud/functions/Context.java:23: warning: no @return
[WARNING] String eventId();
[WARNING] ^
[WARNING] /Users/timmerman/Documents/github/googlecloudplatform/functions-framework-java/functions-framework-api/src/main/java/com/google/cloud/functions/Context.java:26: warning: no @return
[WARNING] String timestamp();
[WARNING] ^
[WARNING] /Users/timmerman/Documents/github/googlecloudplatform/functions-framework-java/functions-framework-api/src/main/java/com/google/cloud/functions/Context.java:29: warning: no @return
[WARNING] String eventType();
[WARNING] ^
[WARNING] …
```
=> fix: remove warnings from mvn install

.github/workflows/lint.yaml
- Adds a basic linting workflow.
- Uses same command as [Java Docs Samples](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/47a7c67b0cd25ad9b23d61335681d75a72877c16/SAMPLE_FORMAT.md#linting)
To be included with https://github.com/GoogleCloudPlatform/functions-framework#languages--test-status matrix
=> ci: add lint workflow

.gitignore, functions-framework-api/pom.xml, functions-framework-api/src/main/java/com/google/cloud/functions/CloudEventsFunction.java, invoker/core/pom.xml, invoker/core/src/main/java/com/google/cloud/functions/invoker/BackgroundFunctionExecutor.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/runner/Invoker.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/IntegrationTest.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/testfunctions/CloudEventSnoop.java, invoker/pom.xml
Since the API is hopefully stable now, rename `ExperimentalCloudEventsFunction`
to `CloudEventsFunction`.
Add support for a `FUNCTION_SIGNATURE_TYPE` of `cloudevent`. Treat it the same
as `background`. (We don't really need `FUNCTION_SIGNATURE_TYPE`, since the
interface implemented by the function class tells us what the signature is.)
Simplify the integration test slightly by removing some intermediary helper
methods.
=> Update the version of the CloudEvents SDK to 2.0.0RC2.

invoker/core/pom.xml, invoker/core/src/main/java/com/google/cloud/functions/invoker/BackgroundFunctionExecutor.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/testfunctions/CloudEventSnoop.java
Also fix the import order in a couple of source files.
=> Define a property for the CloudEvents SDK version to avoid mentioning it three times.

.gitignore
Currently running `mvn install` or `mvn test` causes a bunch of untracked changes to show up in git. Adding `target/` to the root `.gitignore` will recursively ignore all mvn target directories.
=> Ignore all mvn target directories

.github/workflows/conformance.yaml, .gitignore, invoker/conformance/pom.xml, invoker/conformance/src/main/java/com/google/cloud/functions/conformance/CloudEventsConformanceFunction.java, invoker/conformance/src/main/java/com/google/cloud/functions/conformance/HttpConformanceFunction.java, invoker/pom.xml
This commit adds a GCF project that can be used with the [Cloud Functions Conformance tools](https://github.com/GoogleCloudPlatform/functions-framework-conformance) to validate HTTP and CloudEvent functions. It also adds a Github workflow that runs conformance tests on all PRs and commits to master.
=> Add conformance tests

.github/workflows/conformance.yaml, invoker/conformance/pom.xml, invoker/core/src/main/java/com/google/cloud/functions/invoker/GcfEvents.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/GcfEventsTest.java
This commit fixes a few bugs in the code that converts legacy events to
cloud events:
- preserve nulls when serializing JSON
- firebaseauth and firebasedatabase event types
- firebaseauth subject is derived form user ID in event data
- fix code to extract firebasedatabase subject from resourceName
=> Bug fixes for cloud event conversion

README.md
The gradle example on this site https://cloud.google.com/functions/docs/first-java are different then the ones in this README, also the examples in the README have different variations of run.FunctionTarget, runFunction.target. This aligns the example with the one that already exist.
=> Fix Gradle Example Parameters

.github/workflows/conformance.yaml, invoker/conformance/src/main/java/com/google/cloud/functions/conformance/BackgroundEventConformanceFunction.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/BackgroundFunctionExecutor.java
Previously we had been running conformance tests for background function signature types. This PR enables these tests in the conformance Github action.
Running the tests uncovered one bug in which JSON fields with null values were being dropped from the data param passed to RawBackgroundFunctions. Fixing this is a non-breaking change so I bumped the minor verison of the maven package using:
```bash
mvn versions:set -DnewVersion=1.1.0-SNAPSHOT -DprocessAllModules
```
=> Add conformance tests for background events

.github/workflows/conformance.yaml, invoker/core/src/main/java/com/google/cloud/functions/invoker/CloudFunctionsContext.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/GcfEvents.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/GcfEventsTest.java, invoker/core/src/test/resources/firebase-db2.json
This commit updates the logic for converting legacy events to CloudEvents. Specifically two changes were required:
- [firebasedb event location should be inferred from the domain field](https://github.com/GoogleCloudPlatform/functions-framework-conformance/blob/master/docs/mapping.md#firebase-rtdb-events-tentative)
- [messageId and publishTime should be populated in the PubSub message](https://github.com/GoogleCloudPlatform/functions-framework-conformance/blob/master/docs/mapping.md#cloud-pubsub-events)
With this change `validate_mapping` can be re-enabled for cloudevent conformance tests.
=> Update CloudEvent conversion logic

invoker/core/src/main/java/com/google/cloud/functions/invoker/Event.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/BackgroundFunctionExecutorTest.java, invoker/core/src/test/resources/pubsub_background.json, invoker/core/src/test/resources/pubsub_emulator.json
Currently, the functions frameworks are dependent on some private
dataplane event marshalling logic in order to correctly pass PubSub
events to background functions. This commit implements the same
marshalling logic in the FF in order to enable local development using
the [PubSub emulator](https://cloud.google.com/pubsub/docs/emulator).
We have already implemented this change in other function frameworks:
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/272
https://github.com/GoogleCloudPlatform/functions-framework-ruby/pull/100
https://github.com/GoogleCloudPlatform/functions-framework-python/pull/121
https://github.com/GoogleCloudPlatform/functions-framework-go/pull/70
=> fix local development with the Pub/Sub emulator

README.md
Adds detailed badges/links to main packages and CI.
[![Maven Central](https://img.shields.io/maven-central/v/com.google.cloud.functions/functions-framework-api.svg?label=functions-framework-api)](https://search.maven.org/artifact/com.google.cloud.functions/functions-framework-api)
[![Maven Central](https://img.shields.io/maven-central/v/com.google.cloud.functions.invoker/java-function-invoker.svg?label=java-function-invoker)](https://search.maven.org/artifact/com.google.cloud.functions.invoker/java-function-invoker)
[![Java Unit CI](https://github.com/GoogleCloudPlatform/functions-framework-java/actions/workflows/unit.yaml/badge.svg)](https://github.com/GoogleCloudPlatform/functions-framework-java/actions/workflows/unit.yaml)
[![Java Lint …
=> docs: add badges for Maven Central and CI

invoker/core/src/main/java/com/google/cloud/functions/invoker/BackgroundFunctionExecutor.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/HttpFunctionExecutor.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/IntegrationTest.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/testfunctions/ExceptionBackground.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/testfunctions/ExceptionHttp.java
The FF is inconsistent in how it logs errors in the user function
between HTTP functions and Event-driven functions. This change makes it
so that all functions log the same error with the same severity if
the user function throws an exception.
Log level SEVERE is required to be consistent with the Cloud Functions &
Error Reporting
[docs](https://cloud.google.com/error-reporting/docs/setup/nodejs#cloud_functions).
=> fix: make user function exceptions log level SEVERE

invoker/core/src/main/java/com/google/cloud/functions/invoker/runner/Invoker.java
Allow to stop the invoker so it can be easily used inside an integration test like this.
Fixes #18 
```java
// start the invoker without joining to avoid blocking the thread
Invoker invoker = new Invoker(
8081,
"org.example.HelloWorldHttpFunction",
"http",
Thread.currentThread().getContextClassLoader()
);
invoker.startServer(false);
// test the function using RestAssured
when()
.get("http://localhost:8081")
.then()
.statusCode(200)
.body(is("Hello World!"));
// stop the invoker
invoker.stopServer();
```
=> feat: allow to stop the invoker

.kokoro/release.sh
The kokoro run failed due to gpg error:
```
gpg: WARNING: unsafe permissions on homedir `/tmp/gpg'
gpg: keyring `/tmp/gpg/secring.gpg' created
gpg: keyring `/tmp/gpg/pubring.gpg' created
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
```
This fix is ported from https://github.com/GoogleCloudPlatform/appengine-java-standard/blob/main/kokoro/gcp_ubuntu/release.sh#L27-L28
=> chore: update kokoro build to restart gpg agent

.kokoro/release.sh
The GPG credentials we use are stored in keybox format which is a new format since gpg 2.1.
=> chore: use gpg2 to sign the packages

.kokoro/release.sh
Listing all keys exited with code 2 that broke the script.
```
gpg: WARNING: unsafe permissions on homedir '/tmp/gpg'
gpg: /tmp/gpg/trustdb.gpg: trustdb created
gpg: skipped packet of type 12 in keybox
gpg: skipped packet of type 12 in keybox
gpg: skipped packet of type 12 in keybox
gpg: skipped packet of type 12 in keybox
gpg: skipped packet of type 12 in keybox
gpg: skipped packet of type 12 in keybox
gpg: skipped packet of type 12 in keybox
gpg: skipped packet of type 12 in keybox
/tmp/gpg/pubring.kbx
--------------------
...
[ID: 1064458] Command finished after 2 secs, exit value: 2
```
=> chore: don't list all keys in the gpg keybox

invoker/core/pom.xml
Bump jetty version to be the same as GAE java runtimes: https://github.com/GoogleCloudPlatform/appengine-java-standard/blob/main/THIRD-PARTY.txt#L175-L196
fix #132
=> fix: bump jetty version to 9.4.49.v20220914

.kokoro/release.sh
Latest kokoro release failed with error:
```gpg: signing failed: Inappropriate ioctl for device```
According to https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html the env var ```GPG_TTY``` needs to be initialized to ```$(tty)```
Other sources:
1. https://unix.stackexchange.com/questions/257061/gentoo-linux-gpg-encrypts-properly-a-file-passed-through-parameter-but-throws-i/257065#257065
2. https://github.com/keybase/keybase-issues/issues/2798
=> chore: add missing env variable to fix gpg error

function-maven-plugin/pom.xml, functions-framework-api/pom.xml, invoker/pom.xml
Latest kokoro release failed. See https://github.com/GoogleCloudPlatform/functions-framework-java/pull/181 for more details.
It appears that extra flags are needed in gpg v2.1+ which caused the gpg plugin to break. From searching it seems that version 3.0.1 for the maven gpg plugin added logic that makes the plugin work for version v2.1+ of gpg as seen in https://github.com/apache/maven-gpg-plugin/commit/11aca384c4005747d797dcc4857280d0d578d05f/
Sources:
https://stackoverflow.com/questions/53992950/maven-gpg-plugin-failing-with-inappropriate-ioctl-for-device-when-running-unde#comment118063505_53992951
=> chore: update gpg maven plugin to make it compatible with gpg v2.1+

invoker/conformance/pom.xml, invoker/core/pom.xml, invoker/pom.xml, invoker/testfunction/pom.xml
Reverts GoogleCloudPlatform/functions-framework-java#180 
* Revert in order to fix release pipeline.
=> Revert "chore(master): release java-function-invoker 1.2.2-SNAPSHOT"

invoker/conformance/buildpack_pom.xml, invoker/conformance/prerun.sh
The buildpack integration tests were broken by the typed functions PR which introduces a dependency from the `invoker` package on the latest version of `function-framework-api`. 
The buildpack integration tests must build and install the latest versions of both of these packages and must also use the latest versions of the packages in the builder when running the buildpack integration tests. The prior strategy was to do this by installing the latest versions as a special 0.0.0-SNAPSHOT version which is used by the `.pom` file for the buildpack integration tests. Unfortunately, however, this version does not line up with the dependencies in the various components of function framework (i.e. transitive deps between local packages). To cover these cases we should instead use the real version …
=> chore: fix buildpack integration tests

.github/workflows/conformance.yaml, invoker/conformance/pom.xml, invoker/conformance/src/main/java/com/google/cloud/functions/conformance/TypedConformanceFunction.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/runner/Invoker.java
* Makes typed functions compatible with HTTP triggers by updating Invoker to select a `TypedFunctionExecutor` if the signature is `http` and `TypedFunction` interface. This allows `typed` functions to be used on Google Cloud in the place of `http` functions without changing the trigger type.
*  Adds conformance test coverage.
=> fix: typed declaration works correctly with http trigger

function-maven-plugin/pom.xml
Developer and license information was missing from the pom and is required to publish to the Maven central repo.
=> ci: fix function-maven-plugin release

invoker/core/pom.xml
Update invoker manifest to set the `Implementation-Version` key on the generated Jar file. See https://maven.apache.org/shared/maven-archiver/examples/manifest.html
=> fix(functions): include Implementation-Version key in invoker jar manifest

.github/.release-please-manifest.json, function-maven-plugin/pom.xml, invoker/CHANGELOG.md, invoker/conformance/pom.xml, invoker/core/pom.xml, invoker/pom.xml, invoker/testfunction/pom.xml
Reverts GoogleCloudPlatform/functions-framework-java#220
Release failed due to missing version updates in the conformance.pom manifest, reverting to reattempt release.
=> Revert "chore(main): release java-function-invoker 1.3.1"

invoker/core/src/main/java/com/google/cloud/functions/invoker/HttpFunctionExecutor.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/HttpFunctionExecutorTest.java
Adds the same logic that is used to set the Thread Context ClassLoader when handling a request to also apply that same class loader when constructing the handler. 
Addresses issue https://github.com/GoogleCloudPlatform/functions-framework-java/issues/110
=> fix: set Thread Context ClassLoader correctly when invoking handler constructor

invoker/core/src/main/java/com/google/cloud/functions/invoker/runner/Invoker.java
Proposed change to fix https://github.com/GoogleCloudPlatform/functions-framework-java/issues/225.
As explained in the issue, the solution is based on other Jetty handlers: [InetAccessHandler.java](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/InetAccessHandler.java#L212-L229)
Regarding tests, the integration tests were passing because they just check that 404 is returned, but they miss to check that function is not invoked.
I think that an extra test checking that part would be nice, but the current test framework API won't let me easily check that. I may extend a bit the test framework to add this test if you agree.
=> fix: avoid executing function when /favicon.ico or /robots.txt is called

invoker/core/pom.xml, invoker/core/src/main/java/com/google/cloud/functions/invoker/http/TimeoutFilter.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/runner/Invoker.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/IntegrationTest.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/testfunctions/TimeoutHttp.java
* feature: adds timeout limit to jetty server specified by CLOUD_RUN_TIMEOUT_SECONDS
* adds test coverage
=> fix: server times out when specified by CLOUD_RUN_TIMEOUT_SECONDS

.kokoro/release.sh, functions-framework-api/pom.xml
there are two maven-source-plugin specified. I think we ran into the same issue as https://stackoverflow.com/questions/76305897/maven-build-fails-after-upgrading-to-maven-source-plugin-from-3-2-1-to-3-3-0
I am not familiar with Java enough, so decide to just revert it to an old version in the last 1.1.0 release
=> fix: revert maven-source-plugin to 3.2.1

.github/workflows/buildpack-integration-test.yml
the gcr.io/gae-runtimes project is no longer supported, which is causing integration tests to fail in this repo. serverless-runtimes should be used instead.
=> fix: update builder image url to correct project repository

.github/workflows/lint.yaml
axel-op/googlejavaformat-action breaks on JDK 11
=> fix: update lint to use JDK 17 so axel-op/googlejavaformat-action works

.kokoro/release.sh
token is now required for maven publish
=> fix: update release pipeline to use maven token instead of user:password

.github/release-please-config.json
Previous change d31b502 incorrectly added an extra file to the invoker release which is causing automation breakages when the invoker release PRs are created. 
Example of a broken release PR: https://github.com/GoogleCloudPlatform/functions-framework-java/pull/321/commits
Remove config from version bumping.
=> fix: correct release-please-config for invoker/conformance/pom.xml

invoker/core/src/main/java/com/google/cloud/functions/invoker/BackgroundFunctionExecutor.java, invoker/core/src/main/java/com/google/cloud/functions/invoker/gcf/JsonLogHandler.java, invoker/core/src/test/java/com/google/cloud/functions/invoker/IntegrationTest.java
An unnecessary try-catch masked function exceptions and resulted in success response codes even when a function threw. Remove try-catch and add a test case to cover this path for CloudEvents to avoid regression. (Prior tests only covered Legacy event exceptions).
=> fix: correct Cloud Event retry functionality
